# Generated by Django 5.2 on 2025-05-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetEmCook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
    ]
