# Generated by Django 5.2 on 2025-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetEmCook', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
