# Generated by Django 5.2 on 2025-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetEmCook', '0005_remove_recipe_id_recipe_recipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
