# Generated by Django 5.2 on 2025-05-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetEmCook', '0008_remove_profile_name_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default_profile_img.png', null=True, upload_to='users/'),
        ),
    ]
