# Generated by Django 5.2 on 2025-05-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetEmCook', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
